export enum ExpenseCategory {
  UTILITIES = 'UTILITIES',
  FUEL = 'FUEL',
  RAW_MATERIAL = 'RAW_MATERIAL',
  CONSUMABLE = 'CONSUMABLE',
  HARDWARE = 'HARDWARE',
  PAINT = 'PAINT',
  WAGES = 'WAGES',
  TRANSPORT = 'TRANSPORT',
  MAINTENANCE = 'MAINTENANCE',
  RENT = 'RENT',
  OTHER = 'OTHER'
}
